{{- if and .Values.crowdsieve.enabled .Values.crowdsieve.analyzers.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crowdsieve.fullname" . }}-analyzers
  labels:
    {{- include "crowdsieve.labels" . | nindent 4 }}
data:
  {{- if .Values.crowdsieve.analyzers.rules }}
  {{- range $filename, $content := .Values.crowdsieve.analyzers.rules }}
  {{ $filename }}: |
    {{- $content | nindent 4 }}
  {{- end }}
  {{- else }}
  .gitkeep: ""
  {{- end }}
{{- end }}
