{{- if and .Values.crowdsieve.enabled .Values.crowdsieve.analyzers.enabled .Values.crowdsieve.analyzers.grafana }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crowdsieve.fullname" . }}-grafana
  labels:
    {{- include "crowdsieve.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: {{ .Values.crowdsieve.analyzers.grafana.url | quote }}
  token: {{ .Values.crowdsieve.analyzers.grafana.token | quote }}
{{- end }}
