{{- if and .Values.crowdsieve.enabled .Values.crowdsieve.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crowdsieve.serviceAccountName" . }}
  labels:
    {{- include "crowdsieve.labels" . | nindent 4 }}
  {{- with .Values.crowdsieve.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
